"""empty message

Revision ID: ca70c42b5b7a
Revises: 
Create Date: 2019-08-24 16:27:06.681037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca70c42b5b7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=15), nullable=True))
    op.add_column('user', sa.Column('gender', sa.String(length=5), nullable=True))
    op.add_column('user', sa.Column('work', sa.String(length=33), nullable=True))
    op.create_unique_constraint(None, 'user', ['city'])
    op.create_unique_constraint(None, 'user', ['gender'])
    op.create_unique_constraint(None, 'user', ['work'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'work')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
